routes/web.php
<?php

use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\DashboardController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PlanController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PenggunaController;

Route::get('/', function () {
    return view('welcome');
});

Route::get('dashboard', [ DashboardController::class, 'index' ])
	->name('dashboard')
	->middleware(['auth', 'verified']);

Route::view('home', 'home')
	->name('home')
	->middleware(['auth', 'verified']);

Route::middleware(['auth','can:is-admin'])->group(function(){	
	Route::resource('pengguna', PenggunaController::class);

	Route::put('pengguna/{user}/update_keahlian/', [PenggunaController::class, 'update_keahlian'])
		->name('pengguna.update_keahlian');

	Route::put('pengguna/{user}/tambah_bayaran/', [PenggunaController::class, 'tambah_bayaran'])
		->name('pengguna.tambah_bayaran');

	Route::resource('plan', PlanController::class);
});


Route::middleware(['web', 'auth'])->group(function(){
	Route::get('/profile', [ProfileController::class, 'editProfile'])->name('profile');
	Route::post('/profile/avatar', [ProfileController::class, 'updateAvatar'])->name('profile.avatar');
	Route::delete('/profile/avatar', [ProfileController::class, 'removeOldAvatar'])->name('profile.deleteavatar');
	Route::delete('/profile/device/{id}', [ProfileController::class, 'removeDevice'])->name('profile.deletedevice');

	Route::get('/checkout/{plan:code}/{payment_method}', [CheckoutController::class, 'index'])
		->name('checkout.go');

	Route::get('/verify/{payment:payment_code}/{payment_method}', 
		[CheckoutController::class, 'verify'])
		->name('checkout.verify');



});

Route::post('/verify/{payment:payment_code}/{payment_method}', 
[CheckoutController::class, 'verify']);

Route::view('/mail/membership-expired', 'mail.membership-expired', [
	'user' => (object) [ 'name' => 'Karim' ]
]);

app/Http/Controllers/PenggunaController.php
<?php

namespace App\Http\Controllers;

use Carbon\Carbon;
use App\Models\Plan;
use App\Models\User;
use App\Models\Country;
use App\Models\Payment;
use App\Models\Membership;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class PenggunaController extends Controller
{
    /**
     * Display a listing of the resource.
     */

     public function index() {
        $users = User::paginate( 20 );
        return view('pengguna.index', compact('users') );
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('pengguna.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validation_rules = [
            'name' => 'required|string|min:5|max:255',
            'email' => 'required|email|max:255|unique:users',
            'password' => 'required|min:8',
            'role' => 'required'
        ];

        $validated_data = $request->validate( $validation_rules );

        User::create( $validated_data );

        return redirect('/pengguna')->with('success', 'New user has been added');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        echo "<h1>Maklumat Pengguna</h1>";
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {

        $user = User::findOrFail( $id );
        $role_options = User::USER_ROLES;
        $membership_status_options = Membership::MEMBERSHIP_STATUS;

        $countries = [ '' => 'Sila pilih negara' ] + Country::pluck('name', 'id')->toArray();

        $plan_options = [ '' => 'Sila pilih pelan' ] + Plan::getFormattedPlans();

        $membership_is_empty = $user->memberships->isEmpty();

        $payment_methods = [ '' => 'Pilih kaedah bayaran' ] + Payment::PAYMENT_METHODS;

        $js_plans = Plan::getIdPriceJSON();

        return view('pengguna.edit', compact('user', 'role_options', 'plan_options', 
        'membership_status_options', 'countries', 'membership_is_empty', 'payment_methods', 
        'js_plans'));
    }

    public function update_keahlian(Request $request, User $user) {
        $validated_data = $request->validate([
            'plan_id' => 'required',
            'expire_on' => 'required|date',
            'status' => 'required|string'
        ]);

        $membership = $user->memberships()->first();

        if(!$membership) {
            $membership = new Membership();
            $membership->user_id = $user->id;
        }

        $membership->plan_id = $request->input('plan_id');
        $membership->expire_on = Carbon::parse( $request->input('expire_on') );
        $membership->status = $request->input('status');

        $membership->save();

        return redirect()->back()->with('success', 'Membership details has been updated');
    }

    public function tambah_bayaran( Request $request, User $user) {
        $validated_data = $request->validate([
            'plan_id' => 'required',
            'payment_method' => 'required|string',
            'amount' => 'nullable|numeric',
            'new_expiry' => 'nullable|date',
            'remarks' => 'nullable|string'
        ]);

        $update_plan_id = 0;

        if(is_numeric($validated_data['plan_id'])) {
            $plan = Plan::findOrFail($validated_data['plan_id']);
            $update_plan_id = $plan->id;
        }

        $membership = $user->memberships()->first();

        if(!$membership) {
            $membership = new Membership();
            $membership->user_id = $user->id;
            $membership->status = 'active';
        }

        $membership->plan_id = $update_plan_id;

        if($membership->plan_id === 0) {
            $membership->expire_on = Carbon::parse( $validated_data['new_expiry'] );
        } else {
            if( Carbon::parse( $membership->expire_on )->isFuture() ) {
                $membership->expire_on = Carbon::parse($membership->expire_on)->add( $plan->duration );
            } else {
                $membership->expire_on = Carbon::today()->add( $plan->duration );
            }
        }

        $membership->save();

        $payment = new Payment();

        $payment->membership_id = $membership->id; 
        $payment->amount = ( $update_plan_id === 0 ) ? $validated_data['amount'] : $plan->price;
        $payment->payment_method = $validated_data['payment_method'];
        $payment->remarks = $validated_data['remarks'];
        $payment->payment_status = 'completed';
        $payment->payment_code = Str::random(20);

        $payment->save();

        return redirect()->back()->with('success', 'New payment has been recorded');

    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $user = User::findOrFail( $id );

        $validation_rules = [
            'name' => 'required|string|min:5|max:255',
            'email' => 'required|email|max:255|unique:users,email,'.$user->id,
            'role' => 'required',
            'address_1' => 'required|string|max:255',
            'address_2' => 'nullable|string|max:255',
            'city' => 'nullable|string|max:255',
            'state' => 'nullable|string|max:255',
            'postcode' => 'nullable|string|max:10',
            'country_id' => 'required|integer'
        ];

        if( strlen( $request->input('password')) > 0 ) {
            $validation_rules['password'] = 'min:8';
        }

        // dd($validation_rules);

        $validated_data = $request->validate( $validation_rules );

        $user->fill( $validated_data );

        if(strlen( $request->input('password')) > 0) {
            $user->password = Hash::make( $request->input('password') );
        }

        $user->save();

        return redirect('/pengguna/' . $user->id .'/edit')->with('success', 'User has been updated');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

resources/views/pengguna/create.blade.php
@extends('layouts.dashboard')


@section('page-pretitle', 'Admin')
@section('page-title', 'Pengguna Baru')
@section('page-title-actions')
    <!-- Page title actions -->
    <div class="col-auto ms-auto d-print-none">
        <div class="btn-list">

        </div>
    </div>
@endsection

@section('content')


<div class="container-xl">
        <div class="row justify-content-center">
            <div class="col">



    @if(session('success'))  
        <div class="alert alert-success mt-3">{{ session('success') }}</div>
    @endif 


    <div class="card">
        <div class="card-body">

        <form action="/pengguna" method="post">
@csrf


    <div class="mb-3">
        <label for="" class="form-label">Nama</label>
        <input type="text" 
        class="form-control @error('name')) is-invalid @enderror" 
        name="name"
        value="{{ old('name') }}">
        @error('name')
        <div class="invalid-feedback">{{ $message }}</div>
        @enderror 
    </div>

    <div class="mb-3">
        <label for="" class="form-label">Email</label>
        <input type="email" 
        class="form-control @error('email')) is-invalid @enderror" 
        name="email"
        value="{{ old('email') }}" >
        @error('email')
        <div class="invalid-feedback">{{ $message }}</div>
        @enderror         
    </div>

    <div class="mb-3">
        <label for="" class="form-label">Password</label>
        <input type="password" 
        class="form-control @error('password')) is-invalid @enderror" 
        name="password"
        value="{{ old('password') }}">
        @error('password')
        <div class="invalid-feedback">{{ $message }}</div>
        @enderror   
    </div>


    <div class="mb-3 @error('role') is-invalid @enderror">
                <label for="" class="form-label">Role</label>

                <div class="form-check">
                    <input class="form-check-input" type="radio" 
                    id="role-member" name="role" value="member"
                    @if(old('role') == 'member')
                        checked
                    @endif 
                    />
                    <label class="form-check-label" for="role-member">
                        Member
                    </label>
                </div>

                <div class="form-check">
                    <input class="form-check-input" type="radio" 
                    id="role-admin" name="role" value="admin"      
                    
                    @if(old('admin') == 'member')
                        checked
                    @endif                     
                    />
                    <label class="form-check-label" for="role-admin">
                        Admin
                    </label>
                </div>                
            </div>
            @error('role')
                <div class="invalid-feedback">{{ $message }}</div>
            @enderror    

    <button class="btn btn-primary">Simpan</button>

</form>


        </div>

    </div><!-- /.card -->

    </div> <!-- /.col -->
    </div> <!-- /.row -->
    </div> <!-- /.container -->

@endsection

resources/views/pengguna/edit.blade.php
@extends('layouts.dashboard')


@section('page-pretitle', 'Admin')
@section('page-title', 'Edit Pengguna')
@section('page-title-actions')
    <!-- Page title actions -->
    <div class="col-auto ms-auto d-print-none">
        <div class="btn-list">

        </div>
    </div>
@endsection

@section('content')


<div class="container-xl">


    @if(session('success'))
    
        <div class="row">
            <div class="col">
        <div class="alert alert-success mt-3">{{ session('success') }}</div>

        </div>
        </div>
    @endif 

<div class="row justify-content-center mb-5">
    <div class="col-12 col-md-6">

        <div class="card">
            <div class="card-body">


            <form action="{{ route('pengguna.update', $user->id ) }}" method="post">

            @csrf
            @method('put')

            <h3>Maklumat Ahli</h3>

            <x-form.input 
                name="name" label="Nama" type="text" id="name"
                :value="old('name', $user->name)"
                :error="$errors->first('name')"
            />

            <x-form.input 
                name="email" label="Email" type="email" id="email"
                :value="old('email', $user->email)"
                :error="$errors->first('email')"
            />

            <x-form.input 
                name="password" label="Password" type="password" id="password"
                :value="old('password')"
                :error="$errors->first('password')"
            />

            <x-form.radiobutton 
                name="role" id="role" label="Role" :inline="true" 
                :value="old('role', $user->role)"
                :error="$errors->first('role')"
                :options="$role_options"
            />

            <h3>Alamat</h3>


            <x-form.input 
                name="address_1" label="" type="text" id="address_1"
                :value="old('address_1', $user->address_1)"
                :error="$errors->first('address_1')"
            />

            <x-form.input 
                name="address_2" label="" type="text" id="address_2"
                :value="old('address_2', $user->address_2)"
                :error="$errors->first('address_2')"
            />

            <x-form.input 
                name="city" label="Bandar" type="text" id="city"
                :value="old('city', $user->city)"
                :error="$errors->first('city')"
            />

            <x-form.input 
                name="state" label="Negeri" type="text" id="state"
                :value="old('state', $user->state)"
                :error="$errors->first('state')"
            />

            <x-form.input 
                name="postcode" label="Poskod" type="text" id="postcode"
                :value="old('postcode', $user->postcode)"
                :error="$errors->first('postcode')"
            />

            <x-form.select 
                                :options="$countries"
                                label="Pilih Negara"
                                name="country_id"
                                id="country_id"
                                :value="old('country_id', $user->country_id)"
                                :error="$errors->first('country_id')"
                            />  



                <button class="btn btn-primary" type="submit">Simpan</button>

            </form>

            </div>
        </div>

    </div>

    <div class="col-12 col-md-6">

        <div class="card mb-3">
            <div class="card-body">

                <h3>Maklumat Keahlian</h3>

                <form action="{{ route('pengguna.update_keahlian', $user->id) }}" method="post">
                    @csrf
                    @method('put')
                    <input type="hidden" name="action" value="update_membership">

                    <div class="row">
                        <div class="col">

                            @php  
                                //var_dump( $errors )
                            @endphp
                        </div>
                    </div>

                    <div class="row">


                        <div class="col-7">

                            <x-form.select 
                                :options="$plan_options"
                                :error="$errors->first('plan_id')"
                                label="Current Plan"
                                name="plan_id"
                                id="plan_id"
                                :value="(!$membership_is_empty) ? $user->memberships[0]->plan_id : ''"
                            />

                        </div>
                        <div class="col-5">
                            <x-form.input 
                                id="expire_on"
                                :error="$errors->first('expire_on')"
                                name="expire_on"
                                type="date"
                                label="Tarikh Luput"
                                :value="(!$membership_is_empty) ? $user->memberships[0]->expire_on : ''"
                            
                            />


                        </div>
                        <div class="col-12">

                            <x-form.radiobutton 
                                id="status"
                                name="status"
                                label="Status"
                                :options="$membership_status_options"
                                :error="$errors->first('status')"
                                :value="(!$membership_is_empty) ? $user->memberships[0]->status : ''" 
                                :inline="true"
                            
                            />

                        </div>


                        <div class="col-12">

                            <button class="btn btn-primary">Simpan</button>
                        </div>

                    </div>

            
            </form>


            </div>
        </div>

        <div class="card">
            <div class="card-body">
                <h3>Maklumat Bayaran</h3>

                <form action="{{ route('pengguna.tambah_bayaran', $user->id) }}" method="POST">
                @csrf 
                @method('PUT')

                <div class="row">

                <div class="col-7">
                <x-form.select 
                                :options="$plan_options"
                                label="Pilih Pelan"
                                name="plan_id"
                                id="payment_plan_id"
                                :value="null"
                                :error="$errors->first('plan_id')"
                            />                
                </div>

                <div class="col-5">

                <x-form.select 
                                :options="$payment_methods"
                                label="Keadah Bayaran"
                                name="payment_method"
                                id="payment_method"
                                :value="null"
                                :error="$errors->first('payment_method')"
                            /> 

                </div>
                <div class="col-7">
                <x-form.input 
                                id="amount"
                                name="amount"
                                type=" number"
                                :value="null"
                                label="Jumlah"
                                readonly
                            
                            />

                </div>
                <div class="col-5">

                <x-form.input 
                                id="new_expiry"
                                name="new_expiry"
                                type="date"
                                :value="null"
                                label="Tarikh Luput"
                                readonly
                            
                            />                
                </div>
                <div class="col-12">

                <x-form.input 
                                id="remarks"
                                name="remarks"
                                type="text"
                                :value="null"
                                label="Nota"
                            
                            />   

                </div>



                </div>

                <button class="btn btn-primary">Simpan</button>
                </form>


                <h3 class="mt-4">Bayaran Lepas</h3>
            </div><!-- /.card-body --> 
            <table class="table">
                <thead>
                    <tr>
                        <th>Tarikh</th>
                        <th>Jumlah</th>
                        <th>Kaedah</th>
                    </tr>
                </thead>
                <tbody>

                    @if(!$user->memberships->isEmpty() )

                        @if(!$user->memberships[0]->payments->isEmpty())
                            @foreach($user->memberships[0]->payments as $payment)
                                <tr>
                                    <td>{{ $payment->created_at }}</td>
                                    <td>{{ $payment->amount }}</td>
                                    <td>{{ $payment->payment_method }}</td>
                                </tr>
                            @endforeach

                        @endif
                    @endif


                </tbody>
            </table>
        </div><!-- /.card -->


    </div><!-- /.column -->

</div><!-- /.row -->


    </div> <!-- /.container -->

@endsection


@push('js') 
    <script>
        var js_plans = {!! $js_plans !!}
    </script>
    <script src="/js/user-payment.js"></script>
@endpush

resources/views/pengguna/index.blade.php
@extends('layouts.dashboard')


@section('page-pretitle', 'Admin')
@section('page-title', 'Senarai Pengguna')
@section('page-title-actions')
    <!-- Page title actions -->
    <div class="col-auto ms-auto d-print-none">
        <div class="btn-list">
            <a href="{{ route('pengguna.create') }}" class="btn btn-primary d-none d-sm-inline-block" >
                <!-- Download SVG icon from http://tabler-icons.io/i/plus -->
                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><line x1="12" y1="5" x2="12" y2="19" /><line x1="5" y1="12" x2="19" y2="12" /></svg>
                Pengguna baru
            </a>
            <a href="{{ route('pengguna.create') }}" class="btn btn-primary d-sm-none btn-icon" >
                <!-- Download SVG icon from http://tabler-icons.io/i/plus -->
                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><line x1="12" y1="5" x2="12" y2="19" /><line x1="5" y1="12" x2="19" y2="12" /></svg>
            </a>
        </div>
    </div>
@endsection

@section('content')


<div class="container-xl">
        <div class="row justify-content-center">
            <div class="col">



    @if(session('success'))  
        <div class="alert alert-success mt-3">{{ session('success') }}</div>
    @endif 


    <div class="card">

    <div class="card-body pb-0">
    {{ $users->links() }}

    </div>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>NAMA</th>
                <th>EMAIL</th>
                <th>ROLE</th>
                <th>TARIKH DAFTAR</th>
                <th> </th>
            </tr>
        </thead>

        <tbody>
            @foreach( $users as $user )

            <tr>
                <td>{{ $user->id }}</td>
                <td>{{ $user->name }}</td>
                <td>{{ $user->email }}</td>
                <td>{{ $user->role }}</td>
                <td>{{ $user->created_at }}</td>
                <td><a href="{{ route('pengguna.edit', $user->id) }}" class="btn btn-sm btn-primary">EDIT</a></td>
            </tr>

            @endforeach 

        </tbody>

    </table>
<div class="card-body py-0">
{{ $users->links() }}

</div>
    </div><!-- /.card -->

    </div> <!-- /.col -->
    </div> <!-- /.row -->
    </div> <!-- /.container -->

@endsection