routes/web.php
<?php

use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\DashboardController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PlanController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PenggunaController;

Route::get('/', function () {
    return view('welcome');
});

Route::get('dashboard', [ DashboardController::class, 'index' ])
	->name('dashboard')
	->middleware(['auth', 'verified']);

Route::view('home', 'home')
	->name('home')
	->middleware(['auth', 'verified']);

Route::middleware(['auth','can:is-admin'])->group(function(){	
	Route::resource('pengguna', PenggunaController::class);

	Route::put('pengguna/{user}/update_keahlian/', [PenggunaController::class, 'update_keahlian'])
		->name('pengguna.update_keahlian');

	Route::put('pengguna/{user}/tambah_bayaran/', [PenggunaController::class, 'tambah_bayaran'])
		->name('pengguna.tambah_bayaran');

	Route::resource('plan', PlanController::class);
});


Route::middleware(['web', 'auth'])->group(function(){
	Route::get('/profile', [ProfileController::class, 'editProfile'])->name('profile');
	Route::post('/profile/avatar', [ProfileController::class, 'updateAvatar'])->name('profile.avatar');
	Route::delete('/profile/avatar', [ProfileController::class, 'removeOldAvatar'])->name('profile.deleteavatar');
	Route::delete('/profile/device/{id}', [ProfileController::class, 'removeDevice'])->name('profile.deletedevice');

	Route::get('/checkout/{plan:code}/{payment_method}', [CheckoutController::class, 'index'])
		->name('checkout.go');

	Route::get('/verify/{payment:payment_code}/{payment_method}', 
		[CheckoutController::class, 'verify'])
		->name('checkout.verify');



});

Route::post('/verify/{payment:payment_code}/{payment_method}', 
[CheckoutController::class, 'verify']);

Route::view('/mail/membership-expired', 'mail.membership-expired', [
	'user' => (object) [ 'name' => 'Karim' ]
]);

app/Models/Plan.php
<?php

namespace App\Models;

use App\Models\Membership;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Plan extends Model
{
    use HasFactory;

    public const DURATION_OPTIONS = [
        '1 day' => '1 day',
        '1 week' => '1 week',
        '1 month' => '1 month',
        '3 months' => '3 months',
        '6 months' => '6 months',
        '1 year' => '1 year'
    ];

    public const ACTIVE_OPTIONS = [
        '1' => 'Active',
        '0' => 'Inactive'
    ];

    protected $fillable = [
        'name',
        'code',
        'duration',
        'price',
        'active'
    ];   

    protected function price() : Attribute {
        return Attribute::make(
            get: fn ($value) => number_format($value / 100, 2),
            set: fn ($value) => $value * 100

        );
    }

    public function memberships() {
        return $this->hasMany( Membership::class );
    }

    public static function getFormattedPlans() {
        $plans = self::all();

        $formattedPlans = [];

        foreach($plans as $plan) {
            $formattedPlans[ $plan->id ] = $plan->name 
            . " (RM $plan->price - {$plan->duration})";
        }

        return $formattedPlans;
    }

    public static function getIdPriceJSON() {
        $plans = self::all();

        $associative_array = [];

        foreach($plans as $plan) {
            $associative_array[ $plan->id ] = $plan->toArray();
        }

        return json_encode($associative_array);    
    }

}

app/Http/Controllers/PlanController.php
<?php

namespace App\Http\Controllers;

use App\Models\Plan;
use Illuminate\Http\Request;

class PlanController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $plans = Plan::all();

        return view ('plan.index', compact('plans'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $active_options = Plan::ACTIVE_OPTIONS;

        $duration_options = [ "" => "Sila pilih Pelan"] + Plan::DURATION_OPTIONS;

        return view('plan.create', compact('active_options', 'duration_options'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {

        $duration_validation = implode(",",  array_keys(Plan::DURATION_OPTIONS) );
        $active_validation = implode(",",  array_keys(Plan::ACTIVE_OPTIONS) );

        $validated_data = $request->validate([
            'code' => 'required|string|max:20|min:4|unique:plans,code',
            'name' => 'required|string|max:255|min:8',
            'duration' => 'required|in:' . $duration_validation ,
            'price' => 'required|numeric',
            'active' => 'required|in:'. $active_validation
        ]);

        $plan = Plan::create( $validated_data );

        return redirect()->route('plan.index')->with('success', 'Plan created successfully');

    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

resources/views/plan/create.blade.php
@extends('layouts.dashboard')


@section('page-pretitle', 'Admin')
@section('page-title', 'Pelan baru')
@section('page-title-actions')
    <!-- Page title actions -->
    <div class="col-auto ms-auto d-print-none">
        <div class="btn-list">

        </div>
    </div>
@endsection

@section('content')


<div class="container-xl">
        <div class="row justify-content-center">
            <div class="col">



    @if(session('success'))  
        <div class="alert alert-success mt-3">{{ session('success') }}</div>
    @endif 

    <div class="card">

        <div class="card-body">

            <form action="{{ route('plan.store') }}" method="post">
                @csrf 

                <x-form.input 
                    label="Name" type="text" name="name"
                    id="name" :value="old('name')" :error="$errors->first('name')"
                />

                <x-form.input 
                    label="Code" type="text" name="code"
                    id="code" :value="old('code')" :error="$errors->first('code')"
                />

                <x-form.input 
                    label="Price" type="number" name="price"
                    id="price" :value="old('price')" :error="$errors->first('price')"
                />

                <x-form.select 
                    name="duration"
                    id="duration"
                    label="Duration" 
                    :value="old('duration')"
                    :options="$duration_options"
                    :error="$errors->first('duration')"

                />

                <x-form.radiobutton 
                    name="active"
                    id="active"
                    label="Active"
                    :value="old('active')"
                    :options="$active_options"
                    :error="$errors->first('active')"
                    :inline="false"
                />

                <button class="btn btn-primary">Simpan</button>

            </form>

        </div>


    </div><!-- /.card -->

    </div> <!-- /.col -->
    </div> <!-- /.row -->
    </div> <!-- /.container -->

@endsection

resources/views/plan/index.blade.php
@extends('layouts.dashboard')


@section('page-pretitle', 'Admin')
@section('page-title', 'Senarai Pelan')
@section('page-title-actions')
    <!-- Page title actions -->
    <div class="col-auto ms-auto d-print-none">
        <div class="btn-list">
            <a href="{{ route('plan.create') }}" class="btn btn-primary d-none d-sm-inline-block" >
                <!-- Download SVG icon from http://tabler-icons.io/i/plus -->
                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><line x1="12" y1="5" x2="12" y2="19" /><line x1="5" y1="12" x2="19" y2="12" /></svg>
                Pelan baru
            </a>
            <a href="{{ route('plan.create') }}" class="btn btn-primary d-sm-none btn-icon" >
                <!-- Download SVG icon from http://tabler-icons.io/i/plus -->
                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><line x1="12" y1="5" x2="12" y2="19" /><line x1="5" y1="12" x2="19" y2="12" /></svg>
            </a>
        </div>
    </div>
@endsection

@section('content')


<div class="container-xl">
        <div class="row justify-content-center">
            <div class="col">



    @if(session('success'))  
        <div class="alert alert-success mt-3">{{ session('success') }}</div>
    @endif 


    <div class="card">

    
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>NAMA</th>
                <th>CODE</th>
                <th>HARGA</th>
                <th>TEMPOH</th>
                <th> </th>
            </tr>
        </thead>

        <tbody>
            @forelse( $plans as $plan )

            <tr>
                <td>{{ $plan->id }}</td>
                <td>{{ $plan->name }}</td>
                <td>{{ $plan->code }}</td>
                <td>{{ $plan->price }}</td>
                <td>{{ $plan->duration }}</td>
                <td><a href="{{ route('plan.edit', $plan->id) }}" class="btn btn-sm btn-primary">EDIT</a></td>
            </tr>

            @empty 

            <tr>
                <td colspan="6"> Tiada pelan dalam sistem </td>
            </tr>

            @endforelse 

        </tbody>

    </table>
    </div><!-- /.card -->

    </div> <!-- /.col -->
    </div> <!-- /.row -->
    </div> <!-- /.container -->

@endsection